import type { ClaudeSessionEntry, CursorSessionEntry, OpenAISessionEntry, Session } from '$lib/api';
import { renderMarkdown } from './markdown.server';

export type SessionRole = 'user' | 'assistant' | 'tool';

export interface QuestionOptionView {
	label: string;
	description?: string;
	selected: boolean;
}

export interface QuestionView {
	header?: string;
	question: string;
	multiSelect: boolean;
	options: QuestionOptionView[];
	answer?: string;
}

export interface ToolActivity {
	label: string;
	input?: string;
	output?: string;
	isError?: boolean;
	task?: TaskActivityView;
	tasks?: TaskView[];
	persistedOutput?: PersistedOutputView;
	// Structured AskUserQuestion view: the questions asked, their options, and
	// which option(s) the user ended up choosing.
	questions?: QuestionView[];
}

export interface TaskView {
	id: string;
	subject?: string;
	description?: string;
	activeForm?: string;
	status?: string;
	owner?: string;
	blocks: string[];
	blockedBy: string[];
}

export interface TaskActivityView extends TaskView {
	action: 'create' | 'update';
	metadata?: string;
	previousStatus?: string;
	updatedFields: string[];
	success?: boolean;
}

export interface PersistedOutputView {
	path: string;
	size?: number;
}

// A slash command the user ran (e.g. `/clear`). Claude Code records these in the
// user content as XML-ish tags rather than prose; we surface them as a chip.
export interface CommandView {
	name: string;
	args?: string;
	stdout?: string;
}

// A background task notification Claude Code injects into the user content when a
// queued/background command finishes. Surfaced as a status chip.
export interface NotificationView {
	status?: string;
	summary?: string;
	taskId?: string;
	outputFile?: string;
}

// A message is an ordered sequence of parts so that text and tool activity
// render in the order they actually occurred (text → tool → text → tool),
// rather than all prose first followed by a batch of tools.
export type MessagePart =
	| { kind: 'text'; text: string; html: string }
	| { kind: 'tool'; tool: ToolActivity }
	| { kind: 'command'; command: CommandView }
	| { kind: 'notice'; text: string }
	| { kind: 'notification'; notification: NotificationView };

export interface SessionMessageView {
	id: string;
	role: SessionRole;
	timestamp?: string;
	parts: MessagePart[];
	// Derived from `parts` once the view is assembled; kept for the collapsed
	// preview (title text + tool count) where ordering doesn't matter.
	text?: string;
	tools: ToolActivity[];
}

// Claude Code wraps a user-run slash command in these tags inside the user
// content; an optional caveat preamble precedes locally-run command output.
const COMMAND_NAME_RE = /<command-name>([\s\S]*?)<\/command-name>/i;
const COMMAND_ARGS_RE = /<command-args>([\s\S]*?)<\/command-args>/i;
const COMMAND_STDOUT_RE = /<local-command-stdout>([\s\S]*?)<\/local-command-stdout>/i;
const COMMAND_MESSAGE_RE = /<command-message>[\s\S]*?<\/command-message>/i;
// The local-command caveat is boilerplate noise telling the model to ignore the
// command output; strip both the tag-wrapped and bare-line forms.
const CAVEAT_RE =
	/<local-command-caveat>[\s\S]*?<\/local-command-caveat>|Caveat: The messages below were generated by the user while running local commands\.[^\n]*\n?/gi;

// Pull a slash command out of user text, returning the structured command plus
// whatever prose remained around it (so a command bundled with a real message
// still shows both). Returns null when the text isn't a command at all.
function parseCommand(text: string): { command: CommandView; remainder: string } | null {
	const nameMatch = text.match(COMMAND_NAME_RE);
	if (!nameMatch) return null;

	const name = nameMatch[1].trim();
	if (!name) return null;

	const args = text.match(COMMAND_ARGS_RE)?.[1].trim() || undefined;
	const stdout = text.match(COMMAND_STDOUT_RE)?.[1].trim() || undefined;

	const remainder = text
		.replace(COMMAND_NAME_RE, '')
		.replace(COMMAND_MESSAGE_RE, '')
		.replace(COMMAND_ARGS_RE, '')
		.replace(COMMAND_STDOUT_RE, '')
		.trim();

	return { command: { name, args, stdout }, remainder };
}

// Claude Code injects these into the user content: a bracketed marker when the
// user interrupts a turn, and a <task-notification> block when a background task
// finishes. Both are status events, not prose the user wrote. A single user
// message can carry several of them interleaved with real text.
const SPECIAL_BLOCK_RE =
	/\[Request interrupted by user[^\]]*\]|<task-notification>[\s\S]*?<\/task-notification>/gi;

function tagValue(source: string, tag: string): string | undefined {
	return source.match(new RegExp(`<${tag}>([\\s\\S]*?)</${tag}>`, 'i'))?.[1].trim() || undefined;
}

function parseNotification(block: string): NotificationView {
	return {
		status: tagValue(block, 'status'),
		summary: tagValue(block, 'summary'),
		taskId: tagValue(block, 'task-id'),
		outputFile: tagValue(block, 'output-file')
	};
}

// Append user text, lifting slash commands, interrupt markers, and task
// notifications into their own parts, and dropping local-command caveat noise.
function appendUserText(parts: MessagePart[], raw: string | undefined): void {
	const text = raw?.replace(CAVEAT_RE, '').trim();
	if (!text) return;

	// Slash command messages stand alone — handle them whole.
	const parsed = parseCommand(text);
	if (parsed) {
		parts.push({ kind: 'command', command: parsed.command });
		appendText(parts, parsed.remainder);
		return;
	}

	// Walk the text, emitting a part per special block and keeping the prose
	// between blocks in order.
	let lastIndex = 0;
	let matched = false;
	for (const match of text.matchAll(SPECIAL_BLOCK_RE)) {
		matched = true;
		appendText(parts, text.slice(lastIndex, match.index));
		const token = match[0];
		if (token.startsWith('[')) {
			parts.push({ kind: 'notice', text: 'Interrupted by user' });
		} else {
			parts.push({ kind: 'notification', notification: parseNotification(token) });
		}
		lastIndex = match.index + token.length;
	}

	if (!matched) {
		appendText(parts, text);
		return;
	}
	appendText(parts, text.slice(lastIndex));
}

// Append a text block, merging into the trailing text part when one is already
// there so consecutive prose stays a single markdown unit.
function appendText(parts: MessagePart[], raw: string | undefined): void {
	const text = raw?.trim();
	if (!text) return;
	const last = parts.at(-1);
	if (last?.kind === 'text') {
		last.text = `${last.text}\n\n${text}`;
		last.html = renderMarkdown(last.text);
	} else {
		parts.push({ kind: 'text', text, html: renderMarkdown(text) });
	}
}

// Collapse the ordered parts back down to the flat `text`/`tools` fields used by
// the message preview.
function finalizeMessage(message: SessionMessageView): SessionMessageView {
	const textParts: string[] = [];
	const tools: ToolActivity[] = [];
	for (const part of message.parts) {
		if (part.kind === 'text') textParts.push(part.text);
		else if (part.kind === 'command') textParts.push(part.command.name);
		else if (part.kind === 'notice') textParts.push(part.text);
		else if (part.kind === 'notification')
			textParts.push(part.notification.summary ?? 'Task notification');
		else tools.push(part.tool);
	}
	message.text = textParts.join('\n\n').trim() || undefined;
	message.tools = tools;
	return message;
}

export interface SessionView {
	provider: Session['type'];
	title: string;
	sessionIdentifier?: string;
	model?: string;
	cwd?: string;
	branch?: string;
	startedAt?: string;
	endedAt?: string;
	entryCount: number;
	messages: SessionMessageView[];
}

const MAX_TOOL_DETAIL_LENGTH = 20_000;

function formatDetail(value: unknown): string | undefined {
	if (value === undefined || value === null || value === '') return undefined;

	const formatted =
		typeof value === 'string' ? value : JSON.stringify(value, null, 2) || String(value);

	if (formatted.length <= MAX_TOOL_DETAIL_LENGTH) return formatted;

	return `${formatted.slice(0, MAX_TOOL_DETAIL_LENGTH)}\n\n… output truncated`;
}

function titleFromText(text: string | undefined): string | undefined {
	const normalized = text?.replace(/\s+/g, ' ').trim();
	if (!normalized) return undefined;
	return normalized.length > 80 ? `${normalized.slice(0, 77)}…` : normalized;
}

function stripOpenAIEnvironmentContext(text: string | undefined): string | undefined {
	let candidate = text?.trim();
	const environmentContext = /^\s*<environment_context>[\s\S]*?<\/environment_context>\s*/i;

	while (candidate && environmentContext.test(candidate)) {
		candidate = candidate.replace(environmentContext, '');
	}

	return candidate?.trim() || undefined;
}

function openAITitleFromText(text: string | undefined): string | undefined {
	return titleFromText(stripOpenAIEnvironmentContext(text));
}

// OpenAI tool output is either a plain string or content parts; flatten to text.
function openAIOutputText(output: unknown): string {
	if (typeof output === 'string') return output;
	if (Array.isArray(output)) {
		return output
			.map((part) =>
				part && typeof part === 'object' && 'text' in part
					? String((part as { text: unknown }).text)
					: ''
			)
			.join('\n');
	}
	return '';
}

// Heuristic: did a tool (notably apply_patch) report a failure? Used to avoid
// presenting a diff for an edit that was never actually applied.
function isFailureOutput(text: string): boolean {
	const normalized = text.toLowerCase();
	if (!normalized.trim()) return false;

	const status = normalized.match(/(?:^|\n)\s*status:\s*([^\n]+)/)?.[1].trim();
	if (status) return !['completed', 'success', 'succeeded', 'done'].includes(status);

	return (
		/(^|\n)\s*(error|fatal|traceback)\b/.test(normalized) ||
		normalized.includes('failed to apply') ||
		normalized.includes('patch does not apply') ||
		normalized.includes('apply_patch:') ||
		normalized.includes('no such file') ||
		normalized.includes('command failed') ||
		/exit code:?\s*[1-9]/.test(normalized)
	);
}

type OpenAIEvent = Extract<OpenAISessionEntry, { type: 'event_msg' }>['payload'];
type OpenAIPatchApplyEnd = Extract<OpenAIEvent, { type: 'patch_apply_end' }>;

interface OpenAIPatchApplyState {
	isError: boolean;
	output?: string;
}

function appendToolOutput(activity: ToolActivity, output: string | undefined): void {
	if (!output) return;
	activity.output = activity.output ? `${activity.output}\n\n${output}` : output;
}

function openAIPatchApplyOutput(event: OpenAIPatchApplyEnd): string | undefined {
	const stdout = event.stdout.trim();
	const stderr = event.stderr.trim();
	const sections: string[] = [];

	if (!event.success || stdout || stderr) {
		sections.push(`Status: ${event.status || (event.success ? 'success' : 'failed')}`);
	}
	if (stdout) sections.push(`Stdout:\n${stdout}`);
	if (stderr) sections.push(`Stderr:\n${stderr}`);

	return sections.length > 0 ? sections.join('\n\n') : undefined;
}

function applyOpenAIPatchApplyState(
	activity: ToolActivity,
	state: OpenAIPatchApplyState
): void {
	appendToolOutput(activity, state.output);
	activity.isError = Boolean(activity.isError) || state.isError;
}

// AskUserQuestion input carries the questions and their selectable options.
function buildQuestions(input: unknown): QuestionView[] | undefined {
	if (!input || typeof input !== 'object') return undefined;
	const questions = (input as { questions?: unknown }).questions;
	if (!Array.isArray(questions) || questions.length === 0) return undefined;

	return questions.map((raw) => {
		const q = raw as Record<string, unknown>;
		const options = Array.isArray(q.options)
			? q.options.map((rawOption) => {
					const option = rawOption as Record<string, unknown>;
					return {
						label: String(option.label ?? ''),
						description: option.description ? String(option.description) : undefined,
						selected: false
					};
				})
			: [];
		return {
			header: typeof q.header === 'string' ? q.header : undefined,
			question: String(q.question ?? ''),
			multiSelect: Boolean(q.multiSelect),
			options
		};
	});
}

// The user's choice lives in the tool result's `answers` map, keyed by the
// question text; mark the matching option(s) selected and record the raw answer.
function applyAnswers(questions: QuestionView[], result: unknown): void {
	if (!result || typeof result !== 'object') return;
	const answers = (result as { answers?: unknown }).answers;
	if (!answers || typeof answers !== 'object') return;

	for (const question of questions) {
		const answer = (answers as Record<string, unknown>)[question.question];
		if (typeof answer !== 'string') continue;
		question.answer = answer;
		const chosen = question.multiSelect ? answer.split(/,\s*/) : [answer];
		for (const option of question.options) {
			option.selected = chosen.includes(option.label);
		}
	}
}

function valueRecord(value: unknown): Record<string, unknown> | undefined {
	return value && typeof value === 'object' ? (value as Record<string, unknown>) : undefined;
}

function optionalString(value: unknown): string | undefined {
	return typeof value === 'string' && value.length > 0 ? value : undefined;
}

function stringArray(value: unknown): string[] {
	return Array.isArray(value) ? value.filter((item): item is string => typeof item === 'string') : [];
}

function buildTaskActivity(name: string, input: unknown): TaskActivityView | undefined {
	const data = valueRecord(input);
	if (!data) return undefined;

	if (name === 'TaskCreate') {
		return {
			action: 'create',
			id: '',
			subject: optionalString(data.subject),
			description: optionalString(data.description),
			activeForm: optionalString(data.activeForm),
			metadata: formatDetail(data.metadata),
			blocks: [],
			blockedBy: [],
			updatedFields: []
		};
	}

	if (name === 'TaskUpdate') {
		return {
			action: 'update',
			id: optionalString(data.taskId) ?? '',
			subject: optionalString(data.subject),
			description: optionalString(data.description),
			activeForm: optionalString(data.activeForm),
			status: optionalString(data.status),
			owner: optionalString(data.owner),
			metadata: formatDetail(data.metadata),
			blocks: stringArray(data.addBlocks),
			blockedBy: stringArray(data.addBlockedBy),
			updatedFields: []
		};
	}

	return undefined;
}

function applyStructuredToolResult(activity: ToolActivity, result: unknown): void {
	if (activity.questions) applyAnswers(activity.questions, result);

	const data = valueRecord(result);
	if (!data) return;

	const persistedOutputPath = optionalString(data.persistedOutputPath);
	if (persistedOutputPath) {
		activity.persistedOutput = {
			path: persistedOutputPath,
			size: typeof data.persistedOutputSize === 'number' ? data.persistedOutputSize : undefined
		};
	}

	if (!activity.task) return;
	if (activity.task.action === 'create') {
		const task = valueRecord(data.task);
		if (!task) return;
		activity.task.id = optionalString(task.id) ?? activity.task.id;
		activity.task.subject = optionalString(task.subject) ?? activity.task.subject;
		activity.task.success = true;
		return;
	}

	activity.task.id = optionalString(data.taskId) ?? activity.task.id;
	activity.task.success = typeof data.success === 'boolean' ? data.success : undefined;
	activity.task.updatedFields = stringArray(data.updatedFields);
	const statusChange = valueRecord(data.statusChange);
	if (statusChange) {
		activity.task.previousStatus = optionalString(statusChange.from);
		activity.task.status = optionalString(statusChange.to) ?? activity.task.status;
	}
}

function taskReminderView(value: unknown): TaskView | undefined {
	const task = valueRecord(value);
	const id = optionalString(task?.id);
	if (!task || !id) return undefined;
	return {
		id,
		subject: optionalString(task.subject),
		description: optionalString(task.description),
		activeForm: optionalString(task.activeForm),
		status: optionalString(task.status),
		blocks: stringArray(task.blocks),
		blockedBy: stringArray(task.blockedBy)
	};
}

function range(timestamps: Array<string | undefined>) {
	const values = timestamps.filter((value): value is string => Boolean(value));
	return { startedAt: values.at(0), endedAt: values.at(-1) };
}

function claudeText(entry: Extract<ClaudeSessionEntry, { type: 'user' }>): string | undefined {
	const content = entry.message.content;
	if (typeof content === 'string') return content;

	const text = content
		.filter((block) => block.type === 'text')
		.map((block) => block.text)
		.join('\n\n')
		.trim();

	return text || undefined;
}

function claudeView(data: ClaudeSessionEntry[]): SessionView {
	const messages: SessionMessageView[] = [];
	// Tool calls and their results live in separate entries; track each call by
	// id so the result can be merged back into the assistant reply that issued it.
	const toolsById = new Map<string, ToolActivity>();
	let lastAssistant: SessionMessageView | undefined;

	data.forEach((entry, index) => {
		if (entry.type === 'user') {
			const text = claudeText(entry);
			const content = entry.message.content;
			const resultBlocks =
				typeof content === 'string'
					? []
					: content.filter((block) => block.type === 'tool_result');

			const orphanResults: ToolActivity[] = [];
			for (const block of resultBlocks) {
				const existing = toolsById.get(block.tool_use_id);
				const output = formatDetail(block.content);
				if (existing) {
					existing.output = output;
					applyStructuredToolResult(existing, entry.toolUseResult);
					existing.isError =
						(block.is_error ?? false) || (existing.task?.success === false);
				} else {
					orphanResults.push({
						label: block.is_error ? 'Tool error' : 'Tool result',
						output,
						isError: block.is_error ?? false
					});
				}
			}

			if (text) {
				const parts: MessagePart[] = [];
				appendUserText(parts, text);
				if (parts.length > 0) {
					messages.push({
						id: entry.uuid || `claude-${index}`,
						role: 'user',
						timestamp: entry.timestamp,
						parts,
						tools: []
					});
					lastAssistant = undefined;
				}
			}

			if (orphanResults.length > 0) {
				if (lastAssistant) {
					for (const tool of orphanResults) lastAssistant.parts.push({ kind: 'tool', tool });
				} else {
					messages.push({
						id: entry.uuid || `claude-${index}`,
						role: 'tool',
						timestamp: entry.timestamp,
						parts: orphanResults.map((tool) => ({ kind: 'tool', tool })),
						tools: []
					});
				}
			}
		}

		if (entry.type === 'assistant') {
			// Walk the content blocks in order so text and tool calls keep their
			// original sequence (text → tool → text → tool).
			const parts: MessagePart[] = [];
			for (const block of entry.message.content) {
				if (block.type === 'text') {
					appendText(parts, block.text);
				} else if (block.type === 'tool_use') {
					const activity: ToolActivity = {
						label: String(block.name),
						input: formatDetail(block.input),
						task: buildTaskActivity(String(block.name), block.input)
					};
					if (block.name === 'AskUserQuestion') {
						activity.questions = buildQuestions(block.input);
					}
					parts.push({ kind: 'tool', tool: activity });
					if (block.id) toolsById.set(block.id, activity);
				}
			}

			if (parts.length > 0) {
				const message: SessionMessageView = {
					id: entry.uuid || `claude-${index}`,
					role: 'assistant',
					timestamp: entry.timestamp,
					parts,
					tools: []
				};
				messages.push(message);
				lastAssistant = message;
			}
		}

		if (entry.type === 'attachment' && entry.attachment.type === 'task_reminder') {
			const tasks = entry.attachment.content
				.map(taskReminderView)
				.filter((task): task is TaskView => task !== undefined);
			if (tasks.length > 0) {
				messages.push({
					id: entry.uuid || `claude-task-reminder-${index}`,
					role: 'tool',
					timestamp: entry.timestamp,
					parts: [{ kind: 'tool', tool: { label: 'Task list', tasks } }],
					tools: []
				});
			}
		}
	});

	messages.forEach(finalizeMessage);

	const titleEntry = data.find((entry) => entry.type === 'ai-title');
	const lastPromptEntry = data.find((entry) => entry.type === 'last-prompt');
	const commonEntry = data.find(
		(entry) => entry.type === 'user' || entry.type === 'assistant' || entry.type === 'attachment'
	);
	const assistantEntry = data.find((entry) => entry.type === 'assistant');
	const timestamps = data.map((entry) => ('timestamp' in entry ? entry.timestamp : undefined));
	const { startedAt, endedAt } = range(timestamps);

	return {
		provider: 'claude',
		title:
			(titleEntry?.type === 'ai-title' ? titleEntry.aiTitle : undefined) ??
			titleFromText(lastPromptEntry?.type === 'last-prompt' ? (lastPromptEntry.lastPrompt ?? undefined) : undefined) ??
			titleFromText(messages.find((message) => message.role === 'user')?.text) ??
			'Claude session',
		sessionIdentifier: commonEntry && 'sessionId' in commonEntry ? commonEntry.sessionId : undefined,
		model: assistantEntry?.type === 'assistant' ? assistantEntry.message.model : undefined,
		cwd: commonEntry && 'cwd' in commonEntry ? commonEntry.cwd : undefined,
		branch: commonEntry && 'gitBranch' in commonEntry ? commonEntry.gitBranch : undefined,
		startedAt,
		endedAt,
		entryCount: data.length,
		messages
	};
}

function cursorView(data: CursorSessionEntry[]): SessionView {
	const messages: SessionMessageView[] = [];
	// Cursor tool calls do not expose their ids in the session payload, while
	// results do. Pair calls and results in arrival order instead.
	const pendingTools: ToolActivity[] = [];

	data.forEach((entry, index) => {
		if ('type' in entry) return;

		const parts: MessagePart[] = [];
		let hasUserContent = false;
		for (const block of entry.message.content) {
			if (block.type === 'text') {
				if (entry.role === 'user') {
					const previousPartCount = parts.length;
					appendUserText(parts, block.text);
					hasUserContent ||= parts.length > previousPartCount;
				} else {
					appendText(parts, block.text);
				}
			} else if (block.type === 'tool_use') {
				const activity: ToolActivity = {
					label: block.name,
					input: formatDetail(block.input),
					task: buildTaskActivity(block.name, block.input)
				};
				if (block.name === 'AskUserQuestion') {
					activity.questions = buildQuestions(block.input);
				}
				parts.push({ kind: 'tool', tool: activity });
				pendingTools.push(activity);
			} else if (block.type === 'tool_result') {
				const activity = pendingTools.shift();
				const output = formatDetail(block.content);
				const isError = block.is_error ?? false;
				if (activity) {
					activity.output = output;
					applyStructuredToolResult(activity, block.content);
					activity.isError = isError || activity.task?.success === false;
				} else {
					parts.push({
						kind: 'tool',
						tool: { label: isError ? 'Tool error' : 'Tool result', output, isError }
					});
				}
			} else if (block.type === 'image') {
				appendText(parts, '[Image attachment]');
				hasUserContent ||= entry.role === 'user';
			}
		}

		if (parts.length === 0) return;
		messages.push({
			id: `cursor-${index}`,
			role: entry.role === 'user' && !hasUserContent ? 'tool' : entry.role,
			parts,
			tools: []
		});
	});

	messages.forEach(finalizeMessage);

	return {
		provider: 'cursor',
		title:
			titleFromText(messages.find((message) => message.role === 'user')?.text) ?? 'Cursor session',
		entryCount: data.length,
		messages
	};
}

function openAIView(data: OpenAISessionEntry[]): SessionView {
	const messages: SessionMessageView[] = [];
	const hasConversationItems = data.some(
		(entry) =>
			entry.type === 'response_item' &&
			entry.payload.type === 'message' &&
			(entry.payload.role === 'user' || entry.payload.role === 'assistant')
	);

	// Tool calls and outputs arrive as separate items; track each call by id so
	// the output can be merged back into the assistant reply that issued it.
	const toolsById = new Map<string, ToolActivity>();
	const patchApplyByCallId = new Map<string, OpenAIPatchApplyState>();
	let lastAssistant: SessionMessageView | undefined;

	data.forEach((entry, index) => {
		if (entry.type === 'response_item') {
			const item = entry.payload;

			if (item.type === 'message' && item.role !== 'developer') {
				const rawText = item.content
					.map((part) => part.text)
					.join('\n\n')
					.trim();
				const text =
					item.role === 'user' ? stripOpenAIEnvironmentContext(rawText) : rawText || undefined;
				if (text) {
					const parts: MessagePart[] = [];
					appendText(parts, text);
					const message: SessionMessageView = {
						id: `openai-${index}`,
						role: item.role,
						timestamp: entry.timestamp,
						parts,
						tools: []
					};
					messages.push(message);
					lastAssistant = item.role === 'assistant' ? message : undefined;
				}
			}

			if (item.type === 'function_call' || item.type === 'custom_tool_call') {
				const activity: ToolActivity = {
					label: item.name,
					input: formatDetail(item.type === 'function_call' ? item.arguments : item.input)
				};
				if (item.call_id) {
					toolsById.set(item.call_id, activity);
					const patchApplyState = patchApplyByCallId.get(item.call_id);
					if (patchApplyState) {
						applyOpenAIPatchApplyState(activity, patchApplyState);
						patchApplyByCallId.delete(item.call_id);
					}
				}

				// Attach the call to the assistant turn that issued it; if the model
				// went straight to a tool with no text, synthesize an assistant reply.
				if (!lastAssistant) {
					lastAssistant = {
						id: item.call_id || `openai-${index}`,
						role: 'assistant',
						timestamp: entry.timestamp,
						parts: [],
						tools: []
					};
					messages.push(lastAssistant);
				}
				lastAssistant.parts.push({ kind: 'tool', tool: activity });
			}

			if (item.type === 'function_call_output' || item.type === 'custom_tool_call_output') {
				const existing = toolsById.get(item.call_id);
				const text = openAIOutputText(item.output);
				const output = formatDetail(text);
				const isError = isFailureOutput(text);
				if (existing) {
					appendToolOutput(existing, output);
					existing.isError = Boolean(existing.isError) || isError;
				} else if (lastAssistant) {
					lastAssistant.parts.push({ kind: 'tool', tool: { label: 'Tool result', output, isError } });
				} else {
					messages.push({
						id: `${item.call_id}-output-${index}`,
						role: 'tool',
						timestamp: entry.timestamp,
						parts: [{ kind: 'tool', tool: { label: 'Tool result', output, isError } }],
						tools: []
					});
				}
			}
		}

		if (entry.type === 'event_msg') {
			const event = entry.payload;
			if (event.type === 'patch_apply_end') {
				const state: OpenAIPatchApplyState = {
					isError: !event.success,
					output: formatDetail(openAIPatchApplyOutput(event))
				};
				const existing = toolsById.get(event.call_id);
				if (existing) {
					applyOpenAIPatchApplyState(existing, state);
				} else {
					patchApplyByCallId.set(event.call_id, state);
				}
			}

			if (!hasConversationItems && (event.type === 'user_message' || event.type === 'agent_message')) {
				const text =
					event.type === 'user_message'
						? stripOpenAIEnvironmentContext(event.message)
						: event.message.trim() || undefined;
				if (text) {
					const parts: MessagePart[] = [];
					appendText(parts, text);
					const message: SessionMessageView = {
						id: `openai-event-${index}`,
						role: event.type === 'user_message' ? 'user' : 'assistant',
						timestamp: entry.timestamp,
						parts,
						tools: []
					};
					messages.push(message);
					lastAssistant = event.type === 'agent_message' ? message : undefined;
				}
			}
		}
	});

	messages.forEach(finalizeMessage);

	const metaEntry = data.find((entry) => entry.type === 'session_meta');
	const turnEntry = data.find((entry) => entry.type === 'turn_context');
	const meta = metaEntry?.type === 'session_meta' ? metaEntry.payload : undefined;
	const turn = turnEntry?.type === 'turn_context' ? turnEntry.payload : undefined;
	const { startedAt, endedAt } = range(data.map((entry) => entry.timestamp));

	return {
		provider: 'openai',
		title:
			messages
				.filter((message) => message.role === 'user')
				.map((message) => openAITitleFromText(message.text))
				.find((title) => title !== undefined) ?? 'OpenAI session',
		sessionIdentifier: meta?.id,
		model: turn?.model,
		cwd: meta?.cwd ?? turn?.cwd,
		branch: meta?.git.branch,
		startedAt,
		endedAt,
		entryCount: data.length,
		messages
	};
}

// Collapse a whole agent turn into a single block: everything an assistant says
// and does between two user messages — including multi-step tool round-trips that
// arrive as separate entries — is merged. Parts are concatenated in arrival order
// so the interleaving of text and tools is preserved across the merged entries.
function mergeAgentTurns(messages: SessionMessageView[]): SessionMessageView[] {
	const merged: SessionMessageView[] = [];

	for (const message of messages) {
		const previous = merged.at(-1);

		if (message.role !== 'user' && previous && previous.role !== 'user') {
			for (const part of message.parts) {
				if (part.kind === 'text') appendText(previous.parts, part.text);
				else previous.parts.push(part);
			}
			if (message.role === 'assistant') previous.role = 'assistant';
			continue;
		}

		merged.push({ ...message, parts: [...message.parts] });
	}

	return merged.map(finalizeMessage);
}

export function createSessionView(session: Session): SessionView {
	const view =
		session.type === 'claude'
			? claudeView(session.data)
			: session.type === 'cursor'
				? cursorView(session.data)
				: openAIView(session.data);
	return { ...view, messages: mergeAgentTurns(view.messages) };
}
